### ISSUE TITLE
can you help me?a bug

### ISSUE THREAD

**Issue by yahuuu** [codebox/image_augmentor#11]
I encounter A bug that I cant not fix it , can you help me?
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
-------------------- <class 'ops.rotate.Rotate'>
Traceback (most recent call last):
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
Traceback (most recent call last):
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
Traceback (most recent call last):
Traceback (most recent call last):
-------------------- <class 'ops.rotate.Rotate'>
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
Traceback (most recent call last):
-------------------- <class 'ops.rotate.Rotate'>
Traceback (most recent call last):
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
Traceback (most recent call last):
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
-------------------- <class 'ops.rotate.Rotate'>
-------------------- <class 'ops.rotate.Rotate'>
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
Traceback (most recent call last):
TypeError: 'type' object is not iterable
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
TypeError: 'type' object is not iterable
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
Traceback (most recent call last):
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
Traceback (most recent call last):
Traceback (most recent call last):
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
Traceback (most recent call last):
TypeError: 'type' object is not iterable
-------------------- <class 'ops.rotate.Rotate'>
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
TypeError: 'type' object is not iterable
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
Traceback (most recent call last):
TypeError: 'type' object is not iterable
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
Traceback (most recent call last):
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
TypeError: 'type' object is not iterable
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
TypeError: 'type' object is not iterable
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
TypeError: 'type' object is not iterable
TypeError: 'type' object is not iterable
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
Traceback (most recent call last):
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
TypeError: 'type' object is not iterable
TypeError: 'type' object is not iterable
TypeError: 'type' object is not iterable
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
TypeError: 'type' object is not iterable
Traceback (most recent call last):
TypeError: 'type' object is not iterable
Traceback (most recent call last):
TypeError: 'type' object is not iterable
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
  File "data_aug.py", line 43, in work
    out_file_name = build_augmented_file_name(f, op_list)
TypeError: 'type' object is not iterable
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
TypeError: 'type' object is not iterable
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
TypeError: 'type' object is not iterable
TypeError: 'type' object is not iterable
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
TypeError: 'type' object is not iterable
TypeError: 'type' object is not iterable
  File "data_aug.py", line 35, in build_augmented_file_name
    for op in ops:
TypeError: 'type' object is not iterable
TypeError: 'type' object is not iterable
{'processed': 0, 'error': 0, 'skipped_no_match': 0, 'skipped_augmented': 0}

**Comment by yahuuu** [comment]
sorry to disturb U, I fixed it ,and it worked pretty well.

**Comment by codebox** [comment]
Can you describe how you fixed it, in case someone else has the same problem in the future?

**Comment by yahuuu** [comment]
I change some parameters in the  code, but it`s pretty important in the logic. I read the code carefully, It`s my mistake.Hope you delete this issue.
